[[shades]]
name = "vibrance"
default = true  # shader to use during times when there is no other shader scheduled

[[shades]]
name = "blue-light-filter"
start_time = 17:30:00
end_time = 08:30:00

# [[shades]]
# name = "invert-colors"
# default = true
